{% set name = "freediscovery" %}
{% set version = "1.3.1" %}
{% set sha256 = "d266b5cfbf76c12e40bc328f87f1d7d3d4f8567dc8ec59f1bda47ea3b5d49dd5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy >=1.10.0
    - scipy >=0.17.0
    - pandas >=0.19.0
    - scikit-learn >=0.18.1
    - nltk >=3.2
    - requests >=2.10
    - apispec <0.20.0
    - marshmallow >=2.12.2,<2.99
    - flask-apispec >=0.3.2 

test:
  imports:
    - freediscovery
    - freediscovery.cluster

about:
  home: https://github.com/FreeDiscovery/FreeDiscovery
  license: "BSD-3-Clause"
  license_family: "BSD"
  license_file: LICENSE
  summary: 'E-Discovery and Information Retrieval Engine'

  description: |
     FreeDiscovery is built on top of existing machine learning libraries
     (scikit-learn) and exposes a REST API for information retrieval applications. 
  doc_url: https://freediscovery.github.io/doc/stable/
  dev_url: https://github.com/FreeDiscovery/FreeDiscovery

extra:
  recipe-maintainers:
    - rth
