travis:
  secure:
    BINSTAR_TOKEN: MS/c/waQGsJn3/eb3TCfsJrTmlVBQO1dKrE87LddxJ37vUqNDds90fT5gsNFaquRZ8nIiLBlfv3O8rAVt6fN01Vhdvb60Ad++Bb0md8H9Vqj+EnRa/EPCahMyrXEtxDzuadIKfwqbRF0dJzWO/LziFljWBTHaR7e2P7stjTi4QciPnUgKwckrGRpZkIFq0t1DOb5XvmhZIE4XA6kLnnFksjkIZeF3dUsCmTpln77qLtVS8+m7uagrdpX6QOH4CBWmmqAKTae5iK+tLmrmPnrs4XTsNNG+gZHk1lO9MM3OVtsLJ5HUWHi8ZTA1kEh3KSq3ia3URMh4bSwLqDG2FcH7FfpaqQLdZe39gaBXfSB3l2kGRLD0AOQIKZDfCMFBdatenjwnFeaq+u8QZzrnjMx6J2iV/9JChZhEcl9AVCZtjA1KvRCwmSnvrEwecCJenXOCmMv3iO6wPErTAn0F5Rpv5pmiOnbss8/vSoIHk6wM3/RbSrujzNCEnUBYRxNsjTUJITL29VUy0TaYH3ytt6sTadBZsL+Yw1Nul5/481aOkdbKeROIAX1ZZMLrczyuE645ducAsGaWm5laeJs+jdCNQDmC0wTAw0LYylB3477xwkXPnj/V2VaLvrGIMUrEcYhfjtkZ0i78IGHV4x03AnqF97KJXou780LXUzkNtDctz0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
