travis:
  secure:
    BINSTAR_TOKEN: RF+u7fWiuPg1xUkrVOf0uI7piHTp2iXcECcsKdq0P28O+2KtnRnAff+sm1Gv04lg1NO/G35kxDLfe0F6V6j5KdaQfAMUzhRKL46P5abECBrQw98lPyegngeUBvHiVPXjcbhHAICSzeIrJd2zG5Y+l4Rw5+kf1KeFnznt/FzDB4aZpM9BJPVxoqkNAgSmEwht5UbDWA/PROQR+G2UadB4PyEL2DeESfLXusfU6NRiZ94qDZxtfM48hvGjIKTpneoponHmqdVGB11ST0iJE6RYKD4SkDnP7JYO/3AGD8qxvr0bBDATrgCUFRfTmH8HNJHinfdpW/ccfokj2pQpU8zCvIqbagMP5Og21cqH3cEluckYEkkxJikFmggXc/E1pQ7phVYe1cmz/2hbdcflHMVEOwQDvh0fhkxLNCglxEoezakSsHCwORbRVEaFKuVyRUvy90IwwsIvy5zWWcItf6v5skj/PWnCTcmgO+AXRcuaiWMx4zItIq7OPgVYEWVL9FjQlDOwVib5xdzBvyizXYg6unbRbraDygObyZkcvhkXkEuj8Kn9GNGsMk3Bv2cJgvOpij6P/Zl6SgafKybxmHWI4qQGBwpit1NKXM/4uHZpJFpAUVy49ujwspXY1p8aBgFY7g5PG0SuFUTsNZoGSXLKTxRF/8LCmVz4JlCnncR68e8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
